### ISSUE TITLE
Serverr cannot launch on Mc 1.21 with WWEE installed

### ISSUE THREAD

**Issue by Saereth** [Cristelknight/Expanded-Ecosphere#103]
```
13:40:26  [Error] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
- Expanded Ecosphere (expanded_ecosphere) has failed to load correctly
java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
at MC-BOOTSTRAP/fml_loader@4.0.19/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:281) ~[loader-4.0.19.jar%2360!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.19/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:244) ~[loader-4.0.19.jar%2360!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.19/net.neoforged.fml.ModLoader.constructMods(ModLoader.java:152) ~[loader-4.0.19.jar%2360!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.19/net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:142) ~[loader-4.0.19.jar%2360!/:4.0]
at TRANSFORMER/neoforge@21.0.133-beta/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:49) ~[neoforge-21.0.133-beta-universal.jar%23339!/:?]
at TRANSFORMER/neoforge@21.0.133-beta/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34) ~[neoforge-21.0.133-beta-universal.jar%23339!/:?]
at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21-20240613.152323-srg.jar%23338!/:?]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
```
looks like a client screen trying to load on the server

Here is the crashlog from the server
https://mclo.gs/E49jPtu

Let me know if I can help test or provide more info, thanks!

**Comment by Cristelknight** [comment]
I'm not at home currently. But I'll fix it soon-ish when I'm back

**Comment by Cristelknight** [comment]
If you know how to use GitHub and build a file you can just remove the config screen in the NeoForge mod init. I think that should fix it

**Comment by Saereth** [comment]
Yeah sounds good, this current pack is still in early testing so we can wait for a fix, no worries. Ty!

**Comment by pinkyboy910** [comment]
Hi, wondering if this was fixed, seemingly have this issue too?
