### ISSUE TITLE
[Quilt 1.19.2] Mod crashes on startup

### ISSUE THREAD

**Issue by TobiPeterG** [Cristelknight/Expanded-Ecosphere#22]
I'm on WWOO-FABRIC-3.1.9.1.jar
The game crashes with the following message:

java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/resource/loader/BuiltinModResourcePackSource
	at de.cristelknight999.wwoo.utils.Util.getPacks(Util.java:76)
	at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.handler$fgi000$loadPacks(ModResourcePackCreator.java:526)
	at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.method_14453(ModResourcePackCreator.java:57)
	at org.quiltmc.qsl.resource.loader.impl.ModResourcePackProvider.handler$jpi000$onRegister(ModResourcePackProvider.java:549)
	at org.quiltmc.qsl.resource.loader.impl.ModResourcePackProvider.method_14453(ModResourcePackProvider.java:72)
	at org.quiltmc.qsl.resource.loader.impl.ModResourcePackProvider.register(ModResourcePackProvider.java:51)
	at org.quiltmc.qsl.resource.loader.impl.ModResourcePackUtil.createDefaultDataPackSettings(ModResourcePackUtil.java:80)
	at org.quiltmc.qsl.resource.loader.impl.ModResourcePackUtil.<clinit>(ModResourcePackUtil.java:41)
	at org.quiltmc.qsl.resource.loader.impl.ModNioResourcePack.<init>(ModNioResourcePack.java:86)
	at org.quiltmc.qsl.resource.loader.impl.ModNioResourcePack.ofMod(ModNioResourcePack.java:75)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.appendModResourcePacks(ResourceLoaderImpl.java:376)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.buildMinecraftResourcePack(ResourceLoaderImpl.java:392)
	at org.quiltmc.qsl.tag.impl.client.ClientDefaultTagManagerReloader.<init>(ClientDefaultTagManagerReloader.java:56)
	at org.quiltmc.qsl.tag.impl.client.ClientQuiltTagsMod.onInitializeClient(ClientQuiltTagsMod.java:40)
	at net.minecraft.class_310.handler$ilc001$onInit(class_310.java:37971)
	at net.minecraft.class_310.<init>(class_310.java:461)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.resource.loader.BuiltinModResourcePackSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 28 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at de.cristelknight999.wwoo.utils.Util.getPacks(Util.java:76)
	at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.handler$fgi000$loadPacks(ModResourcePackCreator.java:526)
	at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.method_14453(ModResourcePackCreator.java:57)
	at org.quiltmc.qsl.resource.loader.impl.ModResourcePackProvider.handler$jpi000$onRegister(ModResourcePackProvider.java:549)
	at org.quiltmc.qsl.resource.loader.impl.ModResourcePackProvider.method_14453(ModResourcePackProvider.java:72)
	at org.quiltmc.qsl.resource.loader.impl.ModResourcePackProvider.register(ModResourcePackProvider.java:51)
	at org.quiltmc.qsl.resource.loader.impl.ModResourcePackUtil.createDefaultDataPackSettings(ModResourcePackUtil.java:80)
	at org.quiltmc.qsl.resource.loader.impl.ModResourcePackUtil.<clinit>(ModResourcePackUtil.java:41)
	at org.quiltmc.qsl.resource.loader.impl.ModNioResourcePack.<init>(ModNioResourcePack.java:86)
	at org.quiltmc.qsl.resource.loader.impl.ModNioResourcePack.ofMod(ModNioResourcePack.java:75)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.appendModResourcePacks(ResourceLoaderImpl.java:376)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.buildMinecraftResourcePack(ResourceLoaderImpl.java:392)
	at org.quiltmc.qsl.tag.impl.client.ClientDefaultTagManagerReloader.<init>(ClientDefaultTagManagerReloader.java:56)
	at org.quiltmc.qsl.tag.impl.client.ClientQuiltTagsMod.onInitializeClient(ClientQuiltTagsMod.java:40)
	at net.minecraft.class_310.handler$ilc001$onInit(class_310.java:37971)
	at net.minecraft.class_310.<init>(class_310.java:461)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by Cristelknight** [comment]
Quilt isn’t supported yet.
