### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SpiritOTHawk** [Cristelknight/Expanded-Ecosphere#70]
1.20.1
mod v: 3.2.3
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'expanded_ecosphere'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class cristelknight.wwoo.ExpandedEcosphere
		at cristelknight.wwoo.fabric.terrablender.TerrablenderFabricInit.onTerraBlenderInitialized(TerrablenderFabricInit.java:11)
		at terrablender.core.TerraBlenderFabric.lambda$onInitialize$0(TerraBlenderFabric.java:40)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
		at terrablender.core.TerraBlenderFabric.onInitialize(TerraBlenderFabric.java:38)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
		... 9 more
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: net/cristellib/ModLoadingUtil [in thread "Render thread"]
		at cristelknight.wwoo.ExpandedEcosphere.isTerraBlenderLoaded(ExpandedEcosphere.java:46)
		at cristelknight.wwoo.utils.Util.getMode(Util.java:40)
		at cristelknight.wwoo.ExpandedEcosphere.<clinit>(ExpandedEcosphere.java:20)
		at cristelknight.wwoo.fabric.ExpandedEcosphereFabric.onInitialize(ExpandedEcosphereFabric.java:10)
		... 10 more
Caused by: java.lang.NoClassDefFoundError: net/cristellib/ModLoadingUtil
	at cristelknight.wwoo.ExpandedEcosphere.isTerraBlenderLoaded(ExpandedEcosphere.java:46)
	at cristelknight.wwoo.utils.Util.getMode(Util.java:40)
	at cristelknight.wwoo.ExpandedEcosphere.<clinit>(ExpandedEcosphere.java:20)
	at cristelknight.wwoo.fabric.ExpandedEcosphereFabric.onInitialize(ExpandedEcosphereFabric.java:10)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.cristellib.ModLoadingUtil
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 14 more
```

**Comment by xR4YM0ND** [comment]
Same here
[crash report](https://gist.github.com/xR4YM0ND/6340770eb18d596709896a9c7f6ec8c5)

**Comment by Shadowpudding** [comment]
I have the same Issue
[crash-2023-11-10_19.49.49-client.txt](https://github.com/Cristelknight999/Expanded-Ecosphere/files/13322462/crash-2023-11-10_19.49.49-client.txt)

**Comment by Cristelknight** [comment]
should be fixed in a newer cristellib/wwoo version
