### ISSUE TITLE
Expanded Ecosphere 3.2.3 incompatable with CristelLib 1.1.5

### ISSUE THREAD

**Issue by Shadowpudding** [Cristelknight/Expanded-Ecosphere#71]
The other mods do not have any issue, but when I turned Expanded Ecosphere  back on to test if it works now I got this issue. 

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install cristellib, any version between 1.1.3 (inclusive) and 1.1.4 (exclusive) or any version after 1.1.4.
More details:
	 - Mod 'Expanded Ecosphere' (expanded_ecosphere) 3.2.3 requires version 1.1.3 or later of cristellib, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Cristelknight** [comment]
should be fixed
